CREATE TABLE IF NOT EXISTS "__EFMigrationsHistory" (
    "MigrationId" character varying(150) NOT NULL,
    "ProductVersion" character varying(32) NOT NULL,
    CONSTRAINT "PK___EFMigrationsHistory" PRIMARY KEY ("MigrationId")
);

START TRANSACTION;
CREATE TABLE "Agriculteurs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nom" text NOT NULL,
    "Adresse" text NOT NULL,
    "Telephone" text NOT NULL,
    "SocieteId" integer NOT NULL,
    CONSTRAINT "PK_Agriculteurs" PRIMARY KEY ("Id")
);

CREATE TABLE "Categories" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Intitule" text NOT NULL,
    "SocieteId" integer NOT NULL,
    CONSTRAINT "PK_Categories" PRIMARY KEY ("Id")
);

CREATE TABLE "Societes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nom" character varying(200) NOT NULL,
    "NomCommercial" text NOT NULL,
    "MatriculeFiscal" text NOT NULL,
    "ICE" text NOT NULL,
    "Adresse" text NOT NULL,
    "Ville" text NOT NULL,
    "Telephone" character varying(50) NOT NULL,
    "Email" character varying(200) NOT NULL,
    "Plan" text NOT NULL,
    "Devise" text NOT NULL,
    "DateCreation" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_Societes" PRIMARY KEY ("Id")
);

CREATE TABLE "Fermes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NomFerme" text NOT NULL,
    "AgriculteurId" integer NOT NULL,
    "SocieteId" integer NOT NULL,
    CONSTRAINT "PK_Fermes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Fermes_Agriculteurs_AgriculteurId" FOREIGN KEY ("AgriculteurId") REFERENCES "Agriculteurs" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Varietes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Intitule" text NOT NULL,
    "CategorieId" integer NOT NULL,
    "SocieteId" integer NOT NULL,
    CONSTRAINT "PK_Varietes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Varietes_Categories_CategorieId" FOREIGN KEY ("CategorieId") REFERENCES "Categories" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Utilisateurs" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nom" character varying(200) NOT NULL,
    "Email" character varying(200) NOT NULL,
    "MotDePasse" text NOT NULL,
    "Role" character varying(50) NOT NULL,
    "SocieteId" integer NOT NULL,
    "DateCreation" timestamp with time zone NOT NULL DEFAULT (CURRENT_TIMESTAMP),
    "IsActive" boolean NOT NULL DEFAULT TRUE,
    CONSTRAINT "PK_Utilisateurs" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Utilisateurs_Societes_SocieteId" FOREIGN KEY ("SocieteId") REFERENCES "Societes" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Parcelles" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "NomParcelle" text NOT NULL,
    "FermeId" integer NOT NULL,
    "SocieteId" integer NOT NULL,
    CONSTRAINT "PK_Parcelles" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Parcelles_Fermes_FermeId" FOREIGN KEY ("FermeId") REFERENCES "Fermes" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Produites" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "Nom" text NOT NULL,
    "ParcelleId" integer NOT NULL,
    "VarieteId" integer NOT NULL,
    "SocieteId" integer NOT NULL,
    CONSTRAINT "PK_Produites" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Produites_Parcelles_ParcelleId" FOREIGN KEY ("ParcelleId") REFERENCES "Parcelles" ("Id") ON DELETE RESTRICT,
    CONSTRAINT "FK_Produites_Varietes_VarieteId" FOREIGN KEY ("VarieteId") REFERENCES "Varietes" ("Id") ON DELETE RESTRICT
);

CREATE TABLE "EtiquetteFermes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CodeEtiquette" text NOT NULL,
    "AgriculteurId" integer NOT NULL,
    "FermeId" integer NOT NULL,
    "ParcelleId" integer NOT NULL,
    "ProduitId" integer NOT NULL,
    "VarieteId" integer NOT NULL,
    "DateGeneration" timestamp with time zone NOT NULL,
    "Receptionne" boolean NOT NULL,
    "DateReception" timestamp with time zone,
    "SocieteId" integer NOT NULL,
    CONSTRAINT "PK_EtiquetteFermes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_EtiquetteFermes_Agriculteurs_AgriculteurId" FOREIGN KEY ("AgriculteurId") REFERENCES "Agriculteurs" ("Id"),
    CONSTRAINT "FK_EtiquetteFermes_Fermes_FermeId" FOREIGN KEY ("FermeId") REFERENCES "Fermes" ("Id"),
    CONSTRAINT "FK_EtiquetteFermes_Parcelles_ParcelleId" FOREIGN KEY ("ParcelleId") REFERENCES "Parcelles" ("Id"),
    CONSTRAINT "FK_EtiquetteFermes_Produites_ProduitId" FOREIGN KEY ("ProduitId") REFERENCES "Produites" ("Id"),
    CONSTRAINT "FK_EtiquetteFermes_Varietes_VarieteId" FOREIGN KEY ("VarieteId") REFERENCES "Varietes" ("Id")
);

CREATE TABLE "Receptions" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "EtiquetteFermeId" integer NOT NULL,
    "PoidsBrut" numeric(18,2) NOT NULL,
    "Temperature" numeric(5,2) NOT NULL,
    "EtatProduit" text NOT NULL,
    "TypeProduit" text NOT NULL,
    "Observation" text NOT NULL,
    "PaletteId" integer,
    "DateReception" timestamp with time zone NOT NULL,
    "SocieteId" integer NOT NULL,
    "Utilisateur" text NOT NULL,
    CONSTRAINT "PK_Receptions" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Receptions_EtiquetteFermes_EtiquetteFermeId" FOREIGN KEY ("EtiquetteFermeId") REFERENCES "EtiquetteFermes" ("Id")
);

CREATE TABLE "Palettes" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "CodePalette" text NOT NULL,
    "ProduitId" integer NOT NULL,
    "PoidsBrut" numeric(18,2) NOT NULL,
    "QuantiteDisponible" numeric(18,2) NOT NULL,
    "EtatPalette" text NOT NULL,
    "StatutStock" text,
    "DateCreation" timestamp with time zone NOT NULL,
    "Emplacement" text NOT NULL,
    "ReceptionId" integer NOT NULL,
    "SocieteId" integer NOT NULL,
    CONSTRAINT "PK_Palettes" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Palettes_Produites_ProduitId" FOREIGN KEY ("ProduitId") REFERENCES "Produites" ("Id"),
    CONSTRAINT "FK_Palettes_Receptions_ReceptionId" FOREIGN KEY ("ReceptionId") REFERENCES "Receptions" ("Id")
);

CREATE TABLE "SortieStocks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ReceptionId" integer NOT NULL,
    "QuantiteSortie" numeric(18,2) NOT NULL,
    "DateSortie" timestamp with time zone NOT NULL,
    "Utilisateur" text NOT NULL,
    "SocieteId" integer NOT NULL,
    "Observation" text NOT NULL,
    CONSTRAINT "PK_SortieStocks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_SortieStocks_Receptions_ReceptionId" FOREIGN KEY ("ReceptionId") REFERENCES "Receptions" ("Id") ON DELETE CASCADE
);

CREATE TABLE "Stocks" (
    "Id" integer GENERATED BY DEFAULT AS IDENTITY,
    "ReceptionId" integer NOT NULL,
    "ProduitId" integer NOT NULL,
    "VarieteId" integer NOT NULL,
    "QuantiteDisponible" numeric(18,2) NOT NULL,
    "DateEntree" timestamp with time zone NOT NULL,
    "Emplacement" text,
    "SocieteId" integer NOT NULL,
    "EtatStock" text NOT NULL,
    CONSTRAINT "PK_Stocks" PRIMARY KEY ("Id"),
    CONSTRAINT "FK_Stocks_Produites_ProduitId" FOREIGN KEY ("ProduitId") REFERENCES "Produites" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Stocks_Receptions_ReceptionId" FOREIGN KEY ("ReceptionId") REFERENCES "Receptions" ("Id") ON DELETE CASCADE,
    CONSTRAINT "FK_Stocks_Varietes_VarieteId" FOREIGN KEY ("VarieteId") REFERENCES "Varietes" ("Id") ON DELETE CASCADE
);

CREATE INDEX "IX_EtiquetteFermes_AgriculteurId" ON "EtiquetteFermes" ("AgriculteurId");

CREATE INDEX "IX_EtiquetteFermes_FermeId" ON "EtiquetteFermes" ("FermeId");

CREATE INDEX "IX_EtiquetteFermes_ParcelleId" ON "EtiquetteFermes" ("ParcelleId");

CREATE INDEX "IX_EtiquetteFermes_ProduitId" ON "EtiquetteFermes" ("ProduitId");

CREATE INDEX "IX_EtiquetteFermes_VarieteId" ON "EtiquetteFermes" ("VarieteId");

CREATE INDEX "IX_Fermes_AgriculteurId" ON "Fermes" ("AgriculteurId");

CREATE INDEX "IX_Palettes_ProduitId" ON "Palettes" ("ProduitId");

CREATE UNIQUE INDEX "IX_Palettes_ReceptionId" ON "Palettes" ("ReceptionId");

CREATE INDEX "IX_Parcelles_FermeId" ON "Parcelles" ("FermeId");

CREATE INDEX "IX_Produites_ParcelleId" ON "Produites" ("ParcelleId");

CREATE INDEX "IX_Produites_VarieteId" ON "Produites" ("VarieteId");

CREATE INDEX "IX_Receptions_EtiquetteFermeId" ON "Receptions" ("EtiquetteFermeId");

CREATE INDEX "IX_SortieStocks_ReceptionId" ON "SortieStocks" ("ReceptionId");

CREATE INDEX "IX_Stocks_ProduitId" ON "Stocks" ("ProduitId");

CREATE INDEX "IX_Stocks_ReceptionId" ON "Stocks" ("ReceptionId");

CREATE INDEX "IX_Stocks_VarieteId" ON "Stocks" ("VarieteId");

CREATE INDEX "IX_Utilisateurs_SocieteId" ON "Utilisateurs" ("SocieteId");

CREATE INDEX "IX_Varietes_CategorieId" ON "Varietes" ("CategorieId");

INSERT INTO "__EFMigrationsHistory" ("MigrationId", "ProductVersion")
VALUES ('20260720202535_AddParcellesNavigation', '9.0.0');

COMMIT;

