// <auto-generated />
using System;
using AgriTraceAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace TracAgriApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TracAgriApi.Models.Agriculteur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SocieteId")
                        .HasColumnType("integer");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Agriculteurs");
                });

            modelBuilder.Entity("TracAgriApi.Models.Categorie", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SocieteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("TracAgriApi.Models.EtiquetteFerme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgriculteurId")
                        .HasColumnType("integer");

                    b.Property<string>("CodeEtiquette")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateGeneration")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateReception")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FermeId")
                        .HasColumnType("integer");

                    b.Property<int>("ParcelleId")
                        .HasColumnType("integer");

                    b.Property<int>("ProduitId")
                        .HasColumnType("integer");

                    b.Property<bool>("Receptionne")
                        .HasColumnType("boolean");

                    b.Property<int>("SocieteId")
                        .HasColumnType("integer");

                    b.Property<int>("VarieteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgriculteurId");

                    b.HasIndex("FermeId");

                    b.HasIndex("ParcelleId");

                    b.HasIndex("ProduitId");

                    b.HasIndex("VarieteId");

                    b.ToTable("EtiquetteFermes");
                });

            modelBuilder.Entity("TracAgriApi.Models.Ferme", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AgriculteurId")
                        .HasColumnType("integer");

                    b.Property<string>("NomFerme")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SocieteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AgriculteurId");

                    b.ToTable("Fermes");
                });

            modelBuilder.Entity("TracAgriApi.Models.Palette", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CodePalette")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Emplacement")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("EtatPalette")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("PoidsBrut")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ProduitId")
                        .HasColumnType("integer");

                    b.Property<decimal>("QuantiteDisponible")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ReceptionId")
                        .HasColumnType("integer");

                    b.Property<int>("SocieteId")
                        .HasColumnType("integer");

                    b.Property<string>("StatutStock")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ProduitId");

                    b.HasIndex("ReceptionId")
                        .IsUnique();

                    b.ToTable("Palettes");
                });

            modelBuilder.Entity("TracAgriApi.Models.Parcelle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("FermeId")
                        .HasColumnType("integer");

                    b.Property<string>("NomParcelle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SocieteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("FermeId");

                    b.ToTable("Parcelles");
                });

            modelBuilder.Entity("TracAgriApi.Models.Produit", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ParcelleId")
                        .HasColumnType("integer");

                    b.Property<int>("SocieteId")
                        .HasColumnType("integer");

                    b.Property<int>("VarieteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ParcelleId");

                    b.HasIndex("VarieteId");

                    b.ToTable("Produites");
                });

            modelBuilder.Entity("TracAgriApi.Models.Reception", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateReception")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EtatProduit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EtiquetteFermeId")
                        .HasColumnType("integer");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("PaletteId")
                        .HasColumnType("integer");

                    b.Property<decimal>("PoidsBrut")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("SocieteId")
                        .HasColumnType("integer");

                    b.Property<decimal>("Temperature")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("TypeProduit")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Utilisateur")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("EtiquetteFermeId");

                    b.ToTable("Receptions");
                });

            modelBuilder.Entity("TracAgriApi.Models.Societe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Adresse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Devise")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ICE")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("MatriculeFiscal")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomCommercial")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SocieteId")
                        .HasColumnType("integer");

                    b.Property<string>("Telephone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Societes");
                });

            modelBuilder.Entity("TracAgriApi.Models.SortieStock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateSortie")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("QuantiteSortie")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ReceptionId")
                        .HasColumnType("integer");

                    b.Property<int>("SocieteId")
                        .HasColumnType("integer");

                    b.Property<string>("Utilisateur")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ReceptionId");

                    b.ToTable("SortieStocks");
                });

            modelBuilder.Entity("TracAgriApi.Models.Stock", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateEntree")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Emplacement")
                        .HasColumnType("text");

                    b.Property<string>("EtatStock")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ProduitId")
                        .HasColumnType("integer");

                    b.Property<decimal>("QuantiteDisponible")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ReceptionId")
                        .HasColumnType("integer");

                    b.Property<int>("SocieteId")
                        .HasColumnType("integer");

                    b.Property<int>("VarieteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ProduitId");

                    b.HasIndex("ReceptionId");

                    b.HasIndex("VarieteId");

                    b.ToTable("Stocks");
                });

            modelBuilder.Entity("TracAgriApi.Models.Utilisateur", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SocieteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("SocieteId");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("TracAgriApi.Models.Variete", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategorieId")
                        .HasColumnType("integer");

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SocieteId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategorieId");

                    b.ToTable("Varietes");
                });

            modelBuilder.Entity("TracAgriApi.Models.EtiquetteFerme", b =>
                {
                    b.HasOne("TracAgriApi.Models.Agriculteur", "Agriculteur")
                        .WithMany()
                        .HasForeignKey("AgriculteurId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TracAgriApi.Models.Ferme", "Ferme")
                        .WithMany()
                        .HasForeignKey("FermeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TracAgriApi.Models.Parcelle", "Parcelle")
                        .WithMany()
                        .HasForeignKey("ParcelleId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TracAgriApi.Models.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TracAgriApi.Models.Variete", "Variete")
                        .WithMany()
                        .HasForeignKey("VarieteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Agriculteur");

                    b.Navigation("Ferme");

                    b.Navigation("Parcelle");

                    b.Navigation("Produit");

                    b.Navigation("Variete");
                });

            modelBuilder.Entity("TracAgriApi.Models.Ferme", b =>
                {
                    b.HasOne("TracAgriApi.Models.Agriculteur", "Agriculteur")
                        .WithMany("Fermes")
                        .HasForeignKey("AgriculteurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Agriculteur");
                });

            modelBuilder.Entity("TracAgriApi.Models.Palette", b =>
                {
                    b.HasOne("TracAgriApi.Models.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TracAgriApi.Models.Reception", "Reception")
                        .WithOne("Palette")
                        .HasForeignKey("TracAgriApi.Models.Palette", "ReceptionId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Produit");

                    b.Navigation("Reception");
                });

            modelBuilder.Entity("TracAgriApi.Models.Parcelle", b =>
                {
                    b.HasOne("TracAgriApi.Models.Ferme", "Ferme")
                        .WithMany()
                        .HasForeignKey("FermeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ferme");
                });

            modelBuilder.Entity("TracAgriApi.Models.Produit", b =>
                {
                    b.HasOne("TracAgriApi.Models.Parcelle", "Parcelle")
                        .WithMany()
                        .HasForeignKey("ParcelleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("TracAgriApi.Models.Variete", "Variete")
                        .WithMany()
                        .HasForeignKey("VarieteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Parcelle");

                    b.Navigation("Variete");
                });

            modelBuilder.Entity("TracAgriApi.Models.Reception", b =>
                {
                    b.HasOne("TracAgriApi.Models.EtiquetteFerme", "EtiquetteFerme")
                        .WithMany()
                        .HasForeignKey("EtiquetteFermeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("EtiquetteFerme");
                });

            modelBuilder.Entity("TracAgriApi.Models.SortieStock", b =>
                {
                    b.HasOne("TracAgriApi.Models.Reception", "Reception")
                        .WithMany()
                        .HasForeignKey("ReceptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reception");
                });

            modelBuilder.Entity("TracAgriApi.Models.Stock", b =>
                {
                    b.HasOne("TracAgriApi.Models.Produit", "Produit")
                        .WithMany()
                        .HasForeignKey("ProduitId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TracAgriApi.Models.Reception", "Reception")
                        .WithMany()
                        .HasForeignKey("ReceptionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TracAgriApi.Models.Variete", "Variete")
                        .WithMany()
                        .HasForeignKey("VarieteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Produit");

                    b.Navigation("Reception");

                    b.Navigation("Variete");
                });

            modelBuilder.Entity("TracAgriApi.Models.Utilisateur", b =>
                {
                    b.HasOne("TracAgriApi.Models.Societe", "Societe")
                        .WithMany("Utilisateurs")
                        .HasForeignKey("SocieteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Societe");
                });

            modelBuilder.Entity("TracAgriApi.Models.Variete", b =>
                {
                    b.HasOne("TracAgriApi.Models.Categorie", "Categorie")
                        .WithMany("Varietes")
                        .HasForeignKey("CategorieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Categorie");
                });

            modelBuilder.Entity("TracAgriApi.Models.Agriculteur", b =>
                {
                    b.Navigation("Fermes");
                });

            modelBuilder.Entity("TracAgriApi.Models.Categorie", b =>
                {
                    b.Navigation("Varietes");
                });

            modelBuilder.Entity("TracAgriApi.Models.Reception", b =>
                {
                    b.Navigation("Palette");
                });

            modelBuilder.Entity("TracAgriApi.Models.Societe", b =>
                {
                    b.Navigation("Utilisateurs");
                });
#pragma warning restore 612, 618
        }
    }
}
